# Generated by Django 3.2.7 on 2021-10-04 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('image', models.ImageField(blank=True, null=True, upload_to='jobs/')),
                ('location', models.CharField(max_length=500)),
                ('short_desc', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=200)),
                ('vacancy', models.IntegerField()),
                ('job_type', models.CharField(max_length=50)),
                ('salary', models.IntegerField()),
                ('pubished_at', models.DateField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
        ),
    ]
