# Generated by Django 3.2.7 on 2021-10-04 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='country',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('edu', 'Education & Training'), ('sal', 'Sales and Marketing'), ('cum', 'Computer Programing'), ('cus', 'Customer Support'), ('des', 'Design & Multimedia'), ('web', 'Web Development'), ('med', 'Medical/Pharma'), ('eng', 'Engineer/Architects')], max_length=200),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('p', 'part-time'), ('f', 'full-time'), ('i', 'internship')], max_length=50),
        ),
    ]
