# Generated by Django 3.2.7 on 2021-10-04 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20211004_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='requerment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('Education & Training', 'Education & Training'), ('Sales and Marketing', 'Sales and Marketing'), ('Computer Programing', 'Computer Programing'), ('Customer Support', 'Customer Support'), ('Design & Multimedia', 'Design & Multimedia'), ('Web Development', 'Web Development'), ('Medical/Pharma', 'Medical/Pharma'), ('Engineer/Architects', 'Engineer/Architects')], max_length=200),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('part time', 'part-time'), ('full time', 'full-time'), ('internship', 'internship'), ('freelance', 'freelance')], max_length=50),
        ),
    ]
